// Static AI Hub catalog. Integration labels follow the honesty rules in docs/ARCHITECTURE.md §4.16: `native` only for the
// orchestrator's own provider adapters, `openai-compatible` only where the vendor documents an OpenAI-compatible chat
// endpoint, `planned` for tools with an API the orchestrator does not use yet, `no-public-api` otherwise.
// Vendor facts were checked against official sites and docs on 2026-09-15; model names are families, not versions,
// unless the vendor documents them. Logos: public/logos/SOURCES.md.

import type { AITool, ToolLogo } from './types';

const DARK_TILE = '#15161c';
const LIGHT_TILE = '#f5f5f4';

function image(id: string, tile: 'dark' | 'light', fallback: string, accent: string): ToolLogo {
  return { kind: 'image', src: `/logos/${id}.svg`, bg: tile === 'dark' ? DARK_TILE : LIGHT_TILE, fallback, accent };
}

export const HUB_CATALOG: AITool[] = [
  // --- Native orchestrator providers ------------------------------------------------------------------------------
  {
    id: 'chatgpt',
    name: 'ChatGPT & OpenAI API',
    provider: 'OpenAI',
    categories: ['chat', 'coding', 'recherche'],
    subcategories: ['coding:assistent'],
    description: 'Allrounder für Text, Reasoning und Code, per API direkt im Orchestrator nutzbar.',
    tagline: 'Vielseitige Sprachmodelle von OpenAI für Texte, Analysen und Programmierung.',
    capabilities: [
      { label: 'Textgenerierung & Bearbeitung' },
      { label: 'Analyse & Reasoning' },
      { label: 'Programmieren & Debugging' },
      { label: 'Bildverständnis (Vision)' },
      { label: 'Strukturierte Ausgaben (JSON)' },
    ],
    tags: ['Chat', 'Reasoning', 'Coding'],
    logo: { kind: 'icon', value: 'message-square', accent: '#2f7f6b' },
    website: 'https://openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    api: 'yes',
    pricing: 'Nutzungsbasiert (API) · Abo (ChatGPT)',
    popularity: 98,
    addedAt: '2026-09-01',
    recommended: true,
    integration: 'native',
    providerKind: 'openai',
    models: [
      { id: 'gpt-5', label: 'GPT-5' },
      { id: 'gpt-5-mini', label: 'GPT-5 mini' },
    ],
  },
  {
    id: 'claude',
    name: 'Claude',
    provider: 'Anthropic',
    categories: ['chat', 'coding', 'recherche'],
    subcategories: ['coding:assistent', 'coding:agent'],
    description: 'Präzises Denken, lange Kontexte und starke Coding-Fähigkeiten.',
    tagline: 'Modelle von Anthropic für sorgfältige Analysen, lange Dokumente und agentisches Programmieren.',
    capabilities: [
      { label: 'Lange Kontexte & Dokumentanalyse' },
      { label: 'Programmieren & Code-Review' },
      { label: 'Sorgfältiges Reasoning' },
      { label: 'Bildverständnis (Vision)' },
      { label: 'Tool-Nutzung' },
    ],
    tags: ['Chat', 'Analyse', 'Coding'],
    logo: image('claude', 'dark', 'Cl', '#b8603f'),
    website: 'https://www.anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    api: 'yes',
    pricing: 'Nutzungsbasiert (API) · Abo (Claude)',
    popularity: 96,
    addedAt: '2026-09-01',
    recommended: true,
    integration: 'native',
    providerKind: 'anthropic',
    models: [
      { id: 'claude-opus', label: 'Claude Opus' },
      { id: 'claude-sonnet', label: 'Claude Sonnet' },
      { id: 'claude-haiku', label: 'Claude Haiku' },
    ],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    provider: 'Google',
    categories: ['chat', 'recherche', 'coding'],
    subcategories: ['coding:assistent'],
    description: 'Multimodale KI für Text, Bild, Audio und Video mit langen Kontexten.',
    tagline: 'Googles multimodale Modellfamilie, über die Gemini API direkt im Orchestrator nutzbar.',
    capabilities: [
      { label: 'Multimodale Eingaben', detail: 'Text, Bild, Audio und Video' },
      { label: 'Lange Kontexte' },
      { label: 'Programmieren' },
      { label: 'Tool-Nutzung' },
    ],
    tags: ['Chat', 'Multimodal', 'Recherche'],
    logo: image('gemini', 'dark', 'Ge', '#6f5ba3'),
    website: 'https://gemini.google.com',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    api: 'yes',
    pricing: 'Kostenlos + nutzungsbasiert (API)',
    popularity: 92,
    addedAt: '2026-09-01',
    recommended: true,
    integration: 'native',
    providerKind: 'google',
    models: [
      { id: 'gemini-pro', label: 'Gemini Pro' },
      { id: 'gemini-flash', label: 'Gemini Flash' },
    ],
  },

  // --- OpenAI-compatible endpoints ----------------------------------------------------------------------------------
  {
    id: 'mistral',
    name: 'Mistral AI',
    provider: 'Mistral AI',
    categories: ['chat', 'coding'],
    subcategories: ['coding:assistent'],
    description: 'Europäischer Anbieter mit offenen und kommerziellen Modellen, auch für Code.',
    tagline: 'Sprach- und Code-Modelle aus Europa über eine OpenAI-kompatible API.',
    capabilities: [{ label: 'Textgenerierung' }, { label: 'Code (Codestral, Devstral)' }, { label: 'Dokument-OCR' }, { label: 'Offene Modellgewichte' }],
    tags: ['Chat', 'Coding', 'Europa'],
    logo: image('mistral', 'dark', 'Mi', '#c2410c'),
    website: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    api: 'yes',
    pricing: 'Nutzungsbasiert · Abo (Le Chat)',
    popularity: 78,
    addedAt: '2026-09-03',
    recommended: true,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'https://api.mistral.ai/v1',
    models: [
      { id: 'mistral-large', label: 'Mistral Large' },
      { id: 'mistral-medium', label: 'Mistral Medium' },
      { id: 'mistral-small', label: 'Mistral Small' },
      { id: 'codestral', label: 'Codestral' },
      { id: 'devstral', label: 'Devstral' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    provider: 'DeepSeek',
    categories: ['chat', 'coding'],
    subcategories: ['coding:assistent'],
    description: 'Reasoning- und Coding-Modelle über eine OpenAI-kompatible API.',
    tagline: 'Leistungsfähige Modelle mit offenen Gewichten für Reasoning und Programmierung.',
    capabilities: [{ label: 'Reasoning' }, { label: 'Programmieren' }, { label: 'Offene Modellgewichte' }],
    tags: ['Reasoning', 'Coding', 'Open Weights'],
    logo: image('deepseek', 'dark', 'Ds', '#4b63d8'),
    website: 'https://www.deepseek.com',
    docsUrl: 'https://api-docs.deepseek.com',
    api: 'yes',
    pricing: 'Nutzungsbasiert',
    popularity: 74,
    addedAt: '2026-09-03',
    recommended: false,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com',
    models: [],
    modelsNote: 'Die Modellnamen ändern sich häufig; aktuelle Namen stehen in der DeepSeek-Dokumentation.',
  },
  {
    id: 'groq',
    name: 'Groq',
    provider: 'Groq',
    categories: ['chat', 'coding', 'audio'],
    subcategories: ['audio:stt'],
    description: 'Sehr schnelle Inferenz für offene Modelle, OpenAI-kompatibel.',
    tagline: 'Inferenz-Plattform für offene Modelle mit sehr niedriger Latenz.',
    capabilities: [{ label: 'Schnelle LLM-Inferenz' }, { label: 'Offene Modelle' }, { label: 'Spracherkennung (Whisper)' }],
    tags: ['Inferenz', 'Open Source', 'Speed'],
    logo: { kind: 'icon', value: 'gauge', accent: '#b4492f' },
    website: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    api: 'yes',
    pricing: 'Kostenlos + nutzungsbasiert',
    popularity: 70,
    addedAt: '2026-09-04',
    recommended: false,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'https://api.groq.com/openai/v1',
    models: [
      { id: 'llama', label: 'Llama', note: 'Meta' },
      { id: 'gpt-oss', label: 'GPT-OSS', note: 'OpenAI, offene Gewichte' },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    provider: 'OpenRouter',
    categories: ['chat', 'coding'],
    subcategories: [],
    description: 'Eine API für Modelle vieler Anbieter, mit Routing und einheitlicher Abrechnung.',
    tagline: 'Zugriff auf zahlreiche Modellanbieter über einen OpenAI-kompatiblen Endpunkt.',
    capabilities: [{ label: 'Viele Modelle über eine API' }, { label: 'Routing zwischen Anbietern' }, { label: 'Einheitliche Abrechnung' }],
    tags: ['Router', 'Multi-Provider', 'API'],
    logo: image('openrouter', 'dark', 'OR', '#64748b'),
    website: 'https://openrouter.ai',
    docsUrl: 'https://openrouter.ai/docs',
    api: 'yes',
    pricing: 'Nutzungsbasiert (Guthaben)',
    popularity: 72,
    addedAt: '2026-09-04',
    recommended: false,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    models: [],
    modelsNote: 'Modelle vieler Anbieter; die Auswahl hängt von deinem OpenRouter-Konto ab.',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    provider: 'Ollama',
    categories: ['chat', 'coding'],
    subcategories: [],
    description: 'Offene Modelle lokal ausführen. Deine Daten bleiben auf deinem Rechner.',
    tagline: 'Lokale Laufzeit für offene Modelle mit OpenAI-kompatibler Schnittstelle.',
    capabilities: [{ label: 'Lokale Ausführung' }, { label: 'Daten bleiben lokal' }, { label: 'Offene Modelle' }, { label: 'OpenAI-kompatible API' }],
    tags: ['Lokal', 'Open Source', 'Privatsphäre'],
    logo: image('ollama', 'light', 'Ol', '#44403c'),
    website: 'https://ollama.com',
    docsUrl: 'https://docs.ollama.com',
    api: 'yes',
    pricing: 'Kostenlos (lokal) · Abo (Cloud)',
    popularity: 80,
    addedAt: '2026-09-04',
    recommended: true,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'http://localhost:11434/v1',
    models: [
      { id: 'llama', label: 'Llama' },
      { id: 'gemma', label: 'Gemma' },
      { id: 'qwen', label: 'Qwen' },
      { id: 'mistral', label: 'Mistral' },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    provider: 'Cohere',
    categories: ['chat', 'recherche'],
    subcategories: ['recherche:rag'],
    description: 'Modelle für Unternehmen: Chat, Embeddings und Reranking für die Suche.',
    tagline: 'Enterprise-Sprachmodelle mit starkem Fokus auf Suche und RAG.',
    capabilities: [{ label: 'Textgenerierung (Command)' }, { label: 'Embeddings' }, { label: 'Reranking für Suche' }],
    tags: ['RAG', 'Enterprise', 'Embeddings'],
    logo: { kind: 'monogram', value: 'Co', accent: '#9a5a1c' },
    website: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    api: 'yes',
    pricing: 'Kostenlos (Test) + nutzungsbasiert',
    popularity: 58,
    addedAt: '2026-09-05',
    recommended: false,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    models: [
      { id: 'command', label: 'Command' },
      { id: 'embed', label: 'Embed' },
      { id: 'rerank', label: 'Rerank' },
      { id: 'aya', label: 'Aya' },
    ],
  },
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    provider: 'Hugging Face',
    categories: ['chat', 'bild', 'coding'],
    subcategories: ['bild:generierung'],
    description: 'Offene Modelle vieler Anbieter über Inference Providers, Chat OpenAI-kompatibel.',
    tagline: 'Die Plattform für offene Modelle, Datensätze und Inferenz über viele Anbieter.',
    capabilities: [{ label: 'Chat mit offenen Modellen' }, { label: 'Text-zu-Bild und weitere Aufgaben' }, { label: 'Modell-Hub & Datensätze' }],
    tags: ['Open Source', 'Modell-Hub', 'Inferenz'],
    logo: image('hugging-face', 'dark', 'HF', '#b58a00'),
    website: 'https://huggingface.co',
    docsUrl: 'https://huggingface.co/docs/inference-providers',
    api: 'yes',
    pricing: 'Kostenlos (Kontingent) + nutzungsbasiert',
    popularity: 66,
    addedAt: '2026-09-05',
    recommended: false,
    integration: 'openai-compatible',
    providerKind: 'openai-compatible',
    baseUrl: 'https://router.huggingface.co/v1',
    models: [],
    modelsNote: 'Tausende offene Modelle; die OpenAI-kompatible Schnittstelle gilt nur für Chat.',
  },

  // --- Research -----------------------------------------------------------------------------------------------------
  {
    id: 'perplexity',
    name: 'Perplexity',
    provider: 'Perplexity AI',
    categories: ['recherche', 'chat'],
    subcategories: ['recherche:websuche', 'recherche:rag'],
    description: 'Echtzeit-Recherche mit Quellenangaben, per API als Agent und Search API.',
    tagline: 'KI-Suche mit Zitaten. Die Sonar-Chat-API wird durch die Agent API im Responses-Format abgelöst.',
    capabilities: [{ label: 'Websuche mit Quellenangaben' }, { label: 'Aktuelle Informationen' }, { label: 'Search API & Embeddings' }],
    tags: ['Recherche', 'Fakten', 'Web'],
    logo: image('perplexity', 'dark', 'Px', '#1a8fa0'),
    website: 'https://www.perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    api: 'yes',
    pricing: 'Nutzungsbasiert (API) · Abo (Pro)',
    popularity: 86,
    addedAt: '2026-09-02',
    recommended: true,
    integration: 'planned',
    models: [{ id: 'sonar', label: 'Sonar' }],
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    provider: 'Pinecone',
    categories: ['recherche'],
    subcategories: ['recherche:rag'],
    description: 'Vektordatenbank für semantische Suche und RAG-Anwendungen.',
    tagline: 'Verwaltete Vektordatenbank mit integrierten Embeddings und Reranking.',
    capabilities: [{ label: 'Vektordatenbank' }, { label: 'Semantische Suche' }, { label: 'RAG-Assistent' }],
    tags: ['RAG', 'Vektoren', 'API'],
    logo: { kind: 'icon', value: 'database', accent: '#3f4a5c' },
    website: 'https://www.pinecone.io',
    docsUrl: 'https://docs.pinecone.io',
    api: 'yes',
    pricing: 'Kostenlos + nutzungsbasiert',
    popularity: 55,
    addedAt: '2026-09-06',
    recommended: false,
    integration: 'planned',
    models: [],
  },

  // --- Image --------------------------------------------------------------------------------------------------------
  {
    id: 'midjourney',
    name: 'Midjourney',
    provider: 'Midjourney',
    categories: ['bild'],
    subcategories: ['bild:generierung', 'bild:bearbeitung'],
    description: 'Kreative Bildgenerierung über Web und Discord, ohne offizielle API.',
    tagline: 'Bekannt für ästhetische Bilder. Es gibt keine offizielle API; die Nutzungsbedingungen verbieten Automatisierung.',
    capabilities: [{ label: 'Bildgenerierung aus Text' }, { label: 'Varianten & Bearbeitung' }, { label: 'Nutzung über Web & Discord' }],
    tags: ['Bild', 'Design', 'Kreativität'],
    logo: { kind: 'monogram', value: 'Mj', accent: '#4b5563' },
    website: 'https://www.midjourney.com',
    docsUrl: 'https://docs.midjourney.com',
    api: 'no',
    pricing: 'Abo',
    popularity: 84,
    addedAt: '2026-09-02',
    recommended: false,
    integration: 'no-public-api',
    models: [],
  },
  {
    id: 'openai-images',
    name: 'OpenAI Bildgenerierung',
    provider: 'OpenAI',
    categories: ['bild'],
    subcategories: ['bild:generierung', 'bild:bearbeitung'],
    description: 'Bilder aus Text erzeugen und mit Masken oder Referenzen bearbeiten.',
    tagline: 'Die Bild-API von OpenAI für Generierung und Bearbeitung.',
    capabilities: [{ label: 'Bildgenerierung aus Text' }, { label: 'Maskenbasierte Bearbeitung' }, { label: 'Transparente Hintergründe' }],
    tags: ['Bild', 'Design', 'Illustration'],
    logo: { kind: 'icon', value: 'image', accent: '#2f7f6b' },
    website: 'https://openai.com',
    docsUrl: 'https://developers.openai.com/api/docs/guides/image-generation',
    api: 'yes',
    pricing: 'Nutzungsbasiert',
    popularity: 76,
    addedAt: '2026-09-02',
    recommended: false,
    integration: 'planned',
    models: [{ id: 'gpt-image', label: 'GPT Image' }],
  },
  {
    id: 'stability-ai',
    name: 'Stability AI',
    provider: 'Stability AI',
    categories: ['bild', 'audio'],
    subcategories: ['bild:generierung', 'bild:bearbeitung', 'audio:musik'],
    description: 'Bildgenerierung, Bearbeitung und Upscaling, dazu Audio-Modelle.',
    tagline: 'Generative Bild- und Audio-Modelle, teils mit offenen Gewichten.',
    capabilities: [{ label: 'Bildgenerierung' }, { label: 'Bildbearbeitung & Upscaling' }, { label: 'Musik & Sound (Stable Audio)' }],
    tags: ['Bild', 'Design', 'Open Weights'],
    logo: { kind: 'monogram', value: 'St', accent: '#6d3fc4' },
    website: 'https://stability.ai',
    docsUrl: 'https://platform.stability.ai/docs/api-reference',
    api: 'yes',
    pricing: 'Nutzungsbasiert (Credits)',
    popularity: 64,
    addedAt: '2026-09-03',
    recommended: false,
    integration: 'planned',
    models: [
      { id: 'stable-image', label: 'Stable Image' },
      { id: 'stable-diffusion', label: 'Stable Diffusion' },
      { id: 'stable-audio', label: 'Stable Audio' },
    ],
  },
  {
    id: 'black-forest-labs',
    name: 'FLUX',
    provider: 'Black Forest Labs',
    categories: ['bild'],
    subcategories: ['bild:generierung', 'bild:bearbeitung'],
    description: 'Text-zu-Bild und kontextbasierte Bildbearbeitung aus Freiburg.',
    tagline: 'Die FLUX-Modelle von Black Forest Labs für Generierung und präzise Bearbeitung.',
    capabilities: [{ label: 'Text-zu-Bild' }, { label: 'Kontextbasierte Bearbeitung' }, { label: 'Offene Modellvarianten' }],
    tags: ['Bild', 'Bearbeitung', 'Europa'],
    logo: { kind: 'monogram', value: 'BF', accent: '#52525b' },
    website: 'https://bfl.ai',
    docsUrl: 'https://docs.bfl.ai',
    api: 'yes',
    pricing: 'Nutzungsbasiert (Credits)',
    popularity: 62,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [
      { id: 'flux-1-kontext', label: 'FLUX.1 Kontext' },
      { id: 'flux-2', label: 'FLUX.2' },
    ],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    provider: 'Ideogram',
    categories: ['bild'],
    subcategories: ['bild:generierung', 'bild:bearbeitung'],
    description: 'Bildgenerierung mit besonders gutem Text-Rendering in Bildern.',
    tagline: 'Generieren, bearbeiten und remixen, mit lesbarer Typografie im Bild.',
    capabilities: [{ label: 'Bildgenerierung' }, { label: 'Text im Bild' }, { label: 'Remix & Reframe' }],
    tags: ['Bild', 'Typografie', 'Design'],
    logo: { kind: 'monogram', value: 'Id', accent: '#0e6f86' },
    website: 'https://ideogram.ai',
    docsUrl: 'https://developer.ideogram.ai',
    api: 'yes',
    pricing: 'Nutzungsbasiert (API) · Abo',
    popularity: 52,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    provider: 'Adobe',
    categories: ['bild'],
    subcategories: ['bild:generierung', 'bild:bearbeitung'],
    description: 'Generative Bild-KI von Adobe; die API gibt es nur mit Enterprise-Vertrag.',
    tagline: 'Bildgenerierung und Custom Models, integriert in Adobes Kreativ-Werkzeuge.',
    capabilities: [{ label: 'Bildgenerierung' }, { label: 'Produktfotos & Composites' }, { label: 'Custom Models' }],
    tags: ['Bild', 'Enterprise', 'Design'],
    logo: { kind: 'icon', value: 'wand-sparkles', accent: '#b4461b' },
    website: 'https://www.adobe.com/products/firefly.html',
    docsUrl: 'https://developer.adobe.com/firefly-services/docs/firefly-api/',
    api: 'limited',
    pricing: 'Abo (App) · Enterprise (API)',
    popularity: 60,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },

  // --- Video --------------------------------------------------------------------------------------------------------
  {
    id: 'runway',
    name: 'Runway',
    provider: 'Runway',
    categories: ['video', 'bild'],
    subcategories: ['video:generierung', 'video:editing', 'bild:generierung'],
    description: 'KI-gestützte Videogenerierung und Videobearbeitung.',
    tagline: 'Video aus Text und Bild erzeugen oder bestehendes Material mit KI verändern.',
    capabilities: [{ label: 'Text- und Bild-zu-Video' }, { label: 'Video-zu-Video-Bearbeitung' }, { label: 'Bildgenerierung' }],
    tags: ['Video', 'Editing', 'Animation'],
    logo: { kind: 'icon', value: 'clapperboard', accent: '#3b4656' },
    website: 'https://runwayml.com',
    docsUrl: 'https://docs.dev.runwayml.com',
    api: 'yes',
    pricing: 'Abo · nutzungsbasiert (API)',
    popularity: 73,
    addedAt: '2026-09-03',
    recommended: false,
    integration: 'planned',
    models: [
      { id: 'gen-4', label: 'Gen-4' },
      { id: 'aleph', label: 'Aleph' },
    ],
  },
  {
    id: 'luma-ai',
    name: 'Luma AI',
    provider: 'Luma AI',
    categories: ['video', 'bild'],
    subcategories: ['video:generierung', 'bild:generierung', 'bild:bearbeitung'],
    description: 'Dream Machine: Videos und Bilder aus Text und Referenzbildern.',
    tagline: 'Generative Video- und Bildmodelle hinter Dream Machine, per API verfügbar.',
    capabilities: [{ label: 'Text- und Bild-zu-Video' }, { label: 'Bildgenerierung mit Referenzen' }, { label: 'Bildbearbeitung' }],
    tags: ['Video', 'Bild', 'Kreativität'],
    logo: { kind: 'monogram', value: 'Lu', accent: '#5b3fb8' },
    website: 'https://lumalabs.ai',
    docsUrl: 'https://docs.lumalabs.ai',
    api: 'yes',
    pricing: 'Nutzungsbasiert (API) · Abo',
    popularity: 61,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [{ id: 'ray', label: 'Ray', note: 'Video' }],
  },
  {
    id: 'pika',
    name: 'Pika',
    provider: 'Pika',
    categories: ['video'],
    subcategories: ['video:generierung'],
    description: 'Kurze Videos aus Text und Bildern, mit eigener Entwickler-API.',
    tagline: 'Videogenerierung für kreative Clips, als App und über die Pika-API.',
    capabilities: [{ label: 'Text- und Bild-zu-Video' }, { label: 'Effekte für kurze Clips' }],
    tags: ['Video', 'Social', 'Kreativität'],
    logo: { kind: 'monogram', value: 'Pi', accent: '#a3325f' },
    website: 'https://pika.art',
    docsUrl: 'https://dev.pika.art',
    api: 'yes',
    pricing: 'Kostenlos + Abo · nutzungsbasiert (API)',
    popularity: 50,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    provider: 'Synthesia',
    categories: ['video'],
    subcategories: ['video:avatare', 'video:generierung'],
    description: 'Videos mit KI-Avataren für Schulungen, Erklärvideos und Lokalisierung.',
    tagline: 'Avatar-Videos aus Skripten, in vielen Sprachen. API nur in höheren Plänen.',
    capabilities: [{ label: 'KI-Avatare' }, { label: 'Videos aus Skripten' }, { label: 'Dubbing & Lokalisierung' }],
    tags: ['Video', 'Avatare', 'Lernen'],
    logo: { kind: 'icon', value: 'user-round', accent: '#4338ca' },
    website: 'https://www.synthesia.io',
    docsUrl: 'https://docs.synthesia.io',
    api: 'limited',
    pricing: 'Abo · Enterprise',
    popularity: 57,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    provider: 'HeyGen',
    categories: ['video', 'audio'],
    subcategories: ['video:avatare', 'video:generierung', 'video:editing', 'audio:tts'],
    description: 'Avatar-Videos, Videoübersetzung mit Lipsync und Sprachausgabe.',
    tagline: 'Sprechende Avatare und übersetzte Videos, über eine Self-Service-API.',
    capabilities: [{ label: 'KI-Avatare' }, { label: 'Videoübersetzung mit Lipsync' }, { label: 'Sprachausgabe' }],
    tags: ['Video', 'Avatare', 'Übersetzung'],
    logo: { kind: 'monogram', value: 'HG', accent: '#0f6e63' },
    website: 'https://www.heygen.com',
    docsUrl: 'https://developers.heygen.com',
    api: 'yes',
    pricing: 'Abo (App) · nutzungsbasiert (API)',
    popularity: 56,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'google-veo',
    name: 'Veo',
    provider: 'Google',
    categories: ['video'],
    subcategories: ['video:generierung'],
    description: 'Googles Videomodell mit nativem Audio, über Gemini API und Vertex AI.',
    tagline: 'Text- und Bild-zu-Video mit Ton. In der Gemini API nur im kostenpflichtigen Tarif.',
    capabilities: [{ label: 'Text- und Bild-zu-Video' }, { label: 'Nativ erzeugtes Audio' }, { label: 'Video-Verlängerung' }],
    tags: ['Video', 'Audio', 'Google'],
    logo: { kind: 'icon', value: 'film', accent: '#2855b8' },
    website: 'https://deepmind.google/models/veo/',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/video',
    api: 'yes',
    pricing: 'Nutzungsbasiert',
    popularity: 68,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [{ id: 'veo-3', label: 'Veo 3' }],
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    provider: 'Kuaishou',
    categories: ['video', 'bild'],
    subcategories: ['video:generierung', 'video:editing', 'bild:generierung'],
    description: 'Text- und Bild-zu-Video, Lipsync und Bildgenerierung per Open Platform.',
    tagline: 'Videogenerierung von Kuaishou mit Entwickler-Plattform und Prepaid-Paketen.',
    capabilities: [{ label: 'Text- und Bild-zu-Video' }, { label: 'Lipsync' }, { label: 'Bildgenerierung' }],
    tags: ['Video', 'Animation', 'Bild'],
    logo: { kind: 'monogram', value: 'Kl', accent: '#1d6a99' },
    website: 'https://kling.ai',
    docsUrl: 'https://kling.ai/document-api',
    api: 'yes',
    pricing: 'Abo (App) · nutzungsbasiert (API)',
    popularity: 54,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'descript',
    name: 'Descript',
    provider: 'Descript',
    categories: ['video', 'audio'],
    subcategories: ['video:editing', 'audio:stt'],
    description: 'Video und Podcasts über das Transkript schneiden, mit KI-Edits.',
    tagline: 'Textbasierter Video- und Audioschnitt; die API steht zahlenden Nutzern offen.',
    capabilities: [{ label: 'Schnitt über das Transkript' }, { label: 'Automatische Transkription' }, { label: 'KI-Edits (Untertitel, Füllwörter)' }],
    tags: ['Editing', 'Podcast', 'Transkript'],
    logo: { kind: 'icon', value: 'scissors', accent: '#2b4aa6' },
    website: 'https://www.descript.com',
    docsUrl: 'https://docs.descriptapi.com',
    api: 'yes',
    pricing: 'Abo',
    popularity: 53,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },

  // --- Audio & voice ------------------------------------------------------------------------------------------------
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    provider: 'ElevenLabs',
    categories: ['audio'],
    subcategories: ['audio:tts', 'audio:stt', 'audio:musik', 'audio:voice-cloning'],
    description: 'Natürlich klingende Stimmen, Transkription, Musik und Voice-Cloning.',
    tagline: 'Sprach-KI für Sprachausgabe, Spracherkennung, Dubbing und Musik.',
    capabilities: [{ label: 'Text-to-Speech' }, { label: 'Spracherkennung (Scribe)' }, { label: 'Voice-Cloning' }, { label: 'Musik & Soundeffekte' }],
    tags: ['Audio', 'Voice', 'TTS'],
    logo: image('elevenlabs', 'light', 'EL', '#44403c'),
    website: 'https://elevenlabs.io',
    docsUrl: 'https://elevenlabs.io/docs',
    api: 'yes',
    pricing: 'Kostenlos + Abo',
    popularity: 82,
    addedAt: '2026-09-02',
    recommended: true,
    integration: 'planned',
    models: [
      { id: 'eleven-v3', label: 'Eleven v3' },
      { id: 'eleven-multilingual', label: 'Eleven Multilingual' },
      { id: 'eleven-flash', label: 'Eleven Flash' },
      { id: 'scribe', label: 'Scribe', note: 'Spracherkennung' },
    ],
  },
  {
    id: 'openai-speech',
    name: 'OpenAI Speech',
    provider: 'OpenAI',
    categories: ['audio'],
    subcategories: ['audio:tts', 'audio:stt'],
    description: 'Sprachausgabe und Transkription über die OpenAI Audio API.',
    tagline: 'Text-to-Speech mit steuerbarem Stil und präzise Transkription, auch als Stream.',
    capabilities: [{ label: 'Text-to-Speech' }, { label: 'Transkription' }, { label: 'Übersetzung ins Englische' }],
    tags: ['Audio', 'TTS', 'Transkription'],
    logo: { kind: 'icon', value: 'audio-lines', accent: '#2f7f6b' },
    website: 'https://openai.com',
    docsUrl: 'https://developers.openai.com/api/docs/guides/text-to-speech',
    api: 'yes',
    pricing: 'Nutzungsbasiert',
    popularity: 67,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [
      { id: 'gpt-4o-mini-tts', label: 'gpt-4o-mini-tts', note: 'Sprachausgabe' },
      { id: 'gpt-4o-transcribe', label: 'gpt-4o-transcribe', note: 'Transkription' },
      { id: 'whisper-1', label: 'whisper-1', note: 'Transkription' },
    ],
  },
  {
    id: 'deepgram',
    name: 'Deepgram',
    provider: 'Deepgram',
    categories: ['audio'],
    subcategories: ['audio:stt', 'audio:tts'],
    description: 'Spracherkennung in Echtzeit und Batch, dazu Sprachausgabe und Voice Agents.',
    tagline: 'Speech-APIs für Transkription, Sprachausgabe und Sprachagenten.',
    capabilities: [{ label: 'Spracherkennung (Streaming & Batch)' }, { label: 'Text-to-Speech' }, { label: 'Voice-Agent-API' }],
    tags: ['Audio', 'STT', 'Echtzeit'],
    logo: image('deepgram', 'dark', 'Dg', '#0f8a58'),
    website: 'https://deepgram.com',
    docsUrl: 'https://developers.deepgram.com',
    api: 'yes',
    pricing: 'Nutzungsbasiert · Enterprise',
    popularity: 59,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [
      { id: 'nova', label: 'Nova', note: 'Spracherkennung' },
      { id: 'aura', label: 'Aura', note: 'Sprachausgabe' },
    ],
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    provider: 'AssemblyAI',
    categories: ['audio'],
    subcategories: ['audio:stt'],
    description: 'Transkription und Sprachverständnis per API, auch als Stream.',
    tagline: 'Speech-to-Text mit Analysen wie Sprechererkennung und Zusammenfassungen.',
    capabilities: [{ label: 'Spracherkennung (Streaming & Batch)' }, { label: 'Speech Understanding' }, { label: 'Voice-Agent-API' }],
    tags: ['Audio', 'STT', 'Analyse'],
    logo: { kind: 'icon', value: 'captions', accent: '#2d4fb3' },
    website: 'https://www.assemblyai.com',
    docsUrl: 'https://www.assemblyai.com/docs',
    api: 'yes',
    pricing: 'Nutzungsbasiert',
    popularity: 51,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'speechmatics',
    name: 'Speechmatics',
    provider: 'Speechmatics',
    categories: ['audio'],
    subcategories: ['audio:stt', 'audio:tts'],
    description: 'Spracherkennung und Übersetzung in Echtzeit, auch On-Premises.',
    tagline: 'Enterprise-Spracherkennung mit breiter Sprachabdeckung.',
    capabilities: [{ label: 'Spracherkennung (Echtzeit & Batch)' }, { label: 'Übersetzung' }, { label: 'On-Premises-Betrieb' }],
    tags: ['Audio', 'STT', 'Enterprise'],
    logo: { kind: 'icon', value: 'mic', accent: '#6b2fa8' },
    website: 'https://www.speechmatics.com',
    docsUrl: 'https://docs.speechmatics.com',
    api: 'yes',
    pricing: 'Kostenlos (Guthaben) + nutzungsbasiert',
    popularity: 45,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'resemble-ai',
    name: 'Resemble AI',
    provider: 'Resemble AI',
    categories: ['audio'],
    subcategories: ['audio:tts', 'audio:stt', 'audio:voice-cloning'],
    description: 'Voice-Cloning, Sprachausgabe und Erkennung von Deepfake-Audio.',
    tagline: 'Stimmen klonen und erzeugen, mit Wasserzeichen und Deepfake-Erkennung.',
    capabilities: [{ label: 'Voice-Cloning' }, { label: 'Text-to-Speech' }, { label: 'Deepfake-Erkennung' }],
    tags: ['Audio', 'Voice', 'Sicherheit'],
    logo: { kind: 'icon', value: 'audio-waveform', accent: '#136b4f' },
    website: 'https://www.resemble.ai',
    docsUrl: 'https://docs.resemble.ai',
    api: 'yes',
    pricing: 'Nutzungsbasiert · Abo',
    popularity: 44,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'planned',
    models: [{ id: 'chatterbox', label: 'Chatterbox' }],
  },
  {
    id: 'suno',
    name: 'Suno',
    provider: 'Suno',
    categories: ['audio'],
    subcategories: ['audio:musik'],
    description: 'Songs aus Prompts erzeugen. API nur über ein kuratiertes Partnerprogramm.',
    tagline: 'Musik-KI für komplette Songs; ohne öffentliche Self-Service-API.',
    capabilities: [{ label: 'Songs aus Text' }, { label: 'Cover & Stems' }],
    tags: ['Audio', 'Musik', 'Kreativität'],
    logo: image('suno', 'light', 'Su', '#44403c'),
    website: 'https://suno.com',
    docsUrl: null,
    api: 'limited',
    pricing: 'Kostenlos + Abo',
    popularity: 65,
    addedAt: '2026-09-15',
    recommended: false,
    integration: 'no-public-api',
    models: [],
  },

  // --- Coding, productivity, automation -----------------------------------------------------------------------------
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    provider: 'GitHub',
    categories: ['coding'],
    subcategories: ['coding:assistent', 'coding:agent'],
    description: 'KI-Pair-Programming in IDE und GitHub, mit Coding-Agent.',
    tagline: 'Code-Vorschläge, Chat und Agent-Aufgaben. Kein offenes Completion-API für Drittanbieter.',
    capabilities: [{ label: 'Code-Vervollständigung in der IDE' }, { label: 'Chat im Editor' }, { label: 'Coding-Agent für Issues' }],
    tags: ['Coding', 'Entwicklung', 'IDE'],
    logo: image('github-copilot', 'light', 'GC', '#44403c'),
    website: 'https://github.com/features/copilot',
    docsUrl: 'https://docs.github.com/en/copilot',
    api: 'limited',
    pricing: 'Kostenlos + Abo',
    popularity: 88,
    addedAt: '2026-09-02',
    recommended: false,
    integration: 'no-public-api',
    models: [],
  },
  {
    id: 'deepl',
    name: 'DeepL',
    provider: 'DeepL',
    categories: ['produktivitaet'],
    subcategories: [],
    description: 'Professionelle Übersetzungen und Schreibhilfe in hoher Qualität.',
    tagline: 'Übersetzung von Texten und Dokumenten sowie Umformulieren mit DeepL Write.',
    capabilities: [{ label: 'Text- & Dokumentübersetzung' }, { label: 'Umformulieren (Write)' }, { label: 'Glossare' }],
    tags: ['Übersetzung', 'Text', 'Sprachen'],
    logo: image('deepl', 'light', 'DL', '#0f2b46'),
    website: 'https://www.deepl.com',
    docsUrl: 'https://developers.deepl.com',
    api: 'yes',
    pricing: 'Kostenlos + Pro',
    popularity: 77,
    addedAt: '2026-09-03',
    recommended: false,
    integration: 'planned',
    models: [],
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    provider: 'Notion',
    categories: ['produktivitaet'],
    subcategories: [],
    description: 'Schreibt, fasst zusammen und beantwortet Fragen direkt in Notion.',
    tagline: 'KI im Notion-Workspace. Die öffentliche Notion-API bietet keine KI-Endpunkte.',
    capabilities: [{ label: 'Schreiben & Zusammenfassen' }, { label: 'Fragen an den Workspace' }],
    tags: ['Produktivität', 'Text', 'Organisation'],
    logo: image('notion-ai', 'light', 'No', '#44403c'),
    website: 'https://www.notion.com/product/ai',
    docsUrl: 'https://developers.notion.com',
    api: 'limited',
    pricing: 'Kostenlos + Abo',
    popularity: 71,
    addedAt: '2026-09-03',
    recommended: false,
    integration: 'no-public-api',
    models: [],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    provider: 'Zapier',
    categories: ['automation', 'produktivitaet'],
    subcategories: ['automation:workflows', 'automation:integrationen'],
    description: 'Verbindet tausende Apps und automatisiert Abläufe, auch mit KI-Schritten.',
    tagline: 'Workflow-Automation über tausende App-Integrationen, inklusive MCP für KI-Clients.',
    capabilities: [{ label: 'Workflows zwischen Apps' }, { label: 'KI-Schritte & Agents' }, { label: 'MCP für KI-Clients' }],
    tags: ['Automation', 'Apps', 'Workflow'],
    logo: image('zapier', 'dark', 'Za', '#c2410c'),
    website: 'https://zapier.com',
    docsUrl: 'https://docs.zapier.com',
    api: 'yes',
    pricing: 'Kostenlos + Abo',
    popularity: 79,
    addedAt: '2026-09-03',
    recommended: true,
    integration: 'planned',
    models: [],
  },
];

const byId = new Map(HUB_CATALOG.map((tool) => [tool.id, tool]));

export function findTool(id: string): AITool | undefined {
  return byId.get(id);
}
