#!/usr/bin/env node
// Re-fetches the AI Hub brand logos from a pinned Simple Icons release, sanitises them and rewrites
// public/logos/SOURCES.md. Usage: node apps/web/scripts/fetch-logos.mjs
// Brands missing from Simple Icons keep the neutral monogram tile in the catalog (see SOURCES.md).

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sanitizeSvg } from './sanitize-svg.mjs';

const SIMPLE_ICONS_TAG = '16.31.0';
const RAW = `https://raw.githubusercontent.com/simple-icons/simple-icons/${SIMPLE_ICONS_TAG}`;

/** Catalog tool id -> Simple Icons slug. */
export const LOGOS = {
  claude: 'claude',
  gemini: 'googlegemini',
  perplexity: 'perplexity',
  mistral: 'mistralai',
  deepseek: 'deepseek',
  openrouter: 'openrouter',
  ollama: 'ollama',
  'hugging-face': 'huggingface',
  elevenlabs: 'elevenlabs',
  deepgram: 'deepgram',
  suno: 'suno',
  'github-copilot': 'githubcopilot',
  deepl: 'deepl',
  'notion-ai': 'notion',
  zapier: 'zapier',
};

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'public', 'logos');

/** Simple Icons derives the slug from the title unless the data sets one explicitly. */
function titleToSlug(title) {
  const replaced = [...title.toLowerCase()]
    .map((ch) => ({ '+': 'plus', '.': 'dot', '&': 'and', đ: 'd', ħ: 'h', ı: 'i', ĸ: 'k', ŀ: 'l', ł: 'l', ß: 'ss', ŧ: 't' })[ch] ?? ch)
    .join('')
    .normalize('NFD');
  return [...replaced].filter((ch) => (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9')).join('');
}

async function fetchText(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`GET ${url} failed with ${response.status}`);
  return response.text();
}

async function main() {
  const data = JSON.parse(await fetchText(`${RAW}/data/simple-icons.json`));
  const icons = Array.isArray(data) ? data : data.icons;
  const bySlug = new Map(icons.map((icon) => [icon.slug ?? titleToSlug(icon.title), icon]));
  const fetchedOn = new Date().toISOString().slice(0, 10);
  await mkdir(outDir, { recursive: true });

  const rows = [];
  for (const [toolId, slug] of Object.entries(LOGOS)) {
    const meta = bySlug.get(slug);
    if (!meta) throw new Error(`Simple Icons ${SIMPLE_ICONS_TAG} has no icon "${slug}"`);
    const url = `${RAW}/icons/${slug}.svg`;
    const svg = sanitizeSvg(await fetchText(url), { fill: `#${meta.hex.toUpperCase()}` });
    await writeFile(join(outDir, `${toolId}.svg`), svg, 'utf8');
    rows.push(`| \`${toolId}.svg\` | ${meta.title} | ${url} | #${meta.hex.toUpperCase()} | CC0-1.0 (Simple Icons) | ${meta.source ?? 'n/a'} | ${fetchedOn} |`);
    console.log(`wrote ${toolId}.svg (${slug})`);
  }

  const sources = `# AI Hub logo sources

Generated by \`apps/web/scripts/fetch-logos.mjs\`. Every file was sanitised with \`apps/web/scripts/sanitize-svg.mjs\`
(allow-list of shape elements and attributes; scripts, event handlers, styles, foreignObject, external references and
data: URIs removed) and is rendered with \`<img>\`, never inlined.

## Trademark notice

All logos are trademarks of their respective owners. They are used only to identify the corresponding integration
(nominative use). Their use does not imply any affiliation with or endorsement by the trademark owners.

## Files

| File | Brand | Source (pinned tag ${SIMPLE_ICONS_TAG}) | Colour | Licence of the SVG file | Brand source listed by Simple Icons | Fetched |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

Simple Icons releases its icon files under CC0-1.0; the marks themselves stay trademarks of their owners and may be
subject to the owners' brand guidelines.

## Tools without a vendored logo

Tools whose brand is not in Simple Icons ${SIMPLE_ICONS_TAG} (for example OpenAI, Midjourney, Stability AI, Runway,
Groq, Cohere, Pinecone and most video and speech vendors) use the neutral monogram or icon tile defined in
\`apps/web/src/lib/hub/catalog.ts\`. No vendor press-kit assets were downloaded; adding one requires the asset's page URL
and usage terms in this file.
`;
  await writeFile(join(outDir, 'SOURCES.md'), sources, 'utf8');
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
