import { AnalysisOutputSchema, PlanOutputSchema, ReleaseReadinessOutputSchema, ReviewOutputSchema } from '../agents/schemas';
import { releaseReadiness } from './release';
import { classifyCiFailure } from '../ci/classifier';
import type { CheckReport, PullRequestRef } from '../github/port';
import { redactSecrets } from '../security/secrets';
import { ToolDeniedError } from '../tools/tool-router';
import { branchNameFor, commitPrefix, truncate } from './helpers';
import { parseOutput, requestApproval, toolContext, workspaceFor, type StageContext, type StageHandler, type StageOutcome } from './stages';

const passed = (summary: string): StageOutcome => ({ kind: 'passed', summary });

function base(ctx: StageContext) {
  return { projectId: ctx.project.id, taskId: ctx.task.id, runId: ctx.run.id };
}

function orchestratorContext(ctx: StageContext) {
  return toolContext(ctx, 'orchestrator', workspaceFor(ctx.run));
}

function pollLater(ctx: StageContext, summary: string): StageOutcome {
  return { kind: 'wait', summary, resumeAt: new Date(ctx.now.getTime() + ctx.options.ciPollIntervalMs) };
}

export const commitStage: StageHandler = async (ctx) => {
  const { deps, project, run, task } = ctx;
  const repo = project.repo;
  if (!repo) return { kind: 'blocked', reason: 'No repository connected.' };
  const cp = run.checkpoint;
  if (cp.changeset.length === 0) return passed('Nothing to commit.');
  if (cp.pendingCommitSha && cp.pendingCommitVersion === cp.changesetVersion) return passed(`Commit ${cp.pendingCommitSha.slice(0, 7)} already created.`);
  if (cp.commitSha && cp.committedVersion === cp.changesetVersion) return passed('No changes since the last push.');

  cp.baseSha ??= await deps.github.getBranchSha(repo, repo.defaultBranch);
  if (!cp.baseSha) return { kind: 'blocked', reason: `Default branch ${repo.defaultBranch} not found.` };

  const branch = cp.branch ?? branchNameFor(task);
  let head = await deps.github.getBranchSha(repo, branch);
  if (!head) {
    await ctx.tools.invoke('git.branch', { branch, fromSha: cp.baseSha }, orchestratorContext(ctx));
    head = cp.baseSha;
    await deps.events.emit({ type: 'github.branch.created', ...base(ctx), payload: { branch } });
  }
  cp.branch = branch;

  const message = `${commitPrefix(task.kind)}: ${truncate(task.title, 72)}\n\nTask ${task.id}, run ${run.id}.\nGenerated by the AI orchestrator.`;
  const { sha } = await ctx.tools.invoke<{ sha: string }>('git.commit', { branch, parentSha: head, message }, orchestratorContext(ctx));
  cp.pendingCommitSha = sha;
  cp.pendingCommitVersion = cp.changesetVersion;
  return passed(`Commit ${sha.slice(0, 7)} created on ${branch}.`);
};

export const pushStage: StageHandler = async (ctx) => {
  const { deps, run } = ctx;
  const cp = run.checkpoint;
  if (!cp.pendingCommitSha) {
    return cp.commitSha ? passed('Already pushed.') : { kind: 'blocked', reason: 'No commit to push.' };
  }
  const branch = cp.branch!;
  await ctx.tools.invoke('git.push', { branch, sha: cp.pendingCommitSha }, orchestratorContext(ctx));
  cp.commitSha = cp.pendingCommitSha;
  cp.committedVersion = cp.pendingCommitVersion;
  cp.pendingCommitSha = null;
  cp.ciPolls = 0;
  ctx.task = await deps.tasks.update(ctx.task.id, { branch });
  await deps.events.emit({ type: 'github.push', ...base(ctx), payload: { branch, sha: cp.commitSha } });
  return passed(`Pushed ${cp.commitSha.slice(0, 7)} to ${branch}.`);
};

function pullRequestBody(ctx: StageContext): string {
  const { run, task } = ctx;
  const plan = parseOutput(PlanOutputSchema, run.checkpoint.outputs.plan);
  const review = parseOutput(ReviewOutputSchema, run.checkpoint.outputs.review);
  const analysis = parseOutput(AnalysisOutputSchema, run.checkpoint.outputs.analysis);
  const lines = [
    `## Goal`,
    task.goal,
    '',
    '## Acceptance criteria',
    ...(task.acceptanceCriteria.length > 0 ? task.acceptanceCriteria.map((c) => `- [ ] ${c}`) : ['- (none specified)']),
    ...(plan ? ['', '## Approach', plan.approach] : []),
    ...(analysis ? ['', '## Context', truncate(analysis.summary, 1000)] : []),
    '',
    '## Verification',
    run.checkpoint.verification?.summary ?? 'Not run before CI.',
    ...(review ? ['', '## Automated review', `Verdict: ${review.verdict}. ${truncate(review.summary, 800)}`] : []),
    '',
    '## Changes',
    ...run.checkpoint.changeset.map((c) => `- \`${c.action}\` ${c.path}`),
    '',
    `<sub>Created by the AI orchestrator · task \`${task.id}\` · run \`${run.id}\` · cost $${run.costUsd.toFixed(4)}</sub>`,
  ];
  return redactSecrets(lines.join('\n'));
}

export const prStage: StageHandler = async (ctx) => {
  const { deps, project, run, task } = ctx;
  const cp = run.checkpoint;
  if (!cp.branch || !project.repo) return { kind: 'blocked', reason: 'No pushed branch to open a pull request from.' };
  const pr = await ctx.tools.invoke<PullRequestRef>(
    'github.pr.create',
    { head: cp.branch, base: project.repo.defaultBranch, title: `${task.title}`.slice(0, 250), body: pullRequestBody(ctx) },
    orchestratorContext(ctx),
  );
  cp.prNumber = pr.number;
  cp.prUrl = pr.url;
  ctx.task = await deps.tasks.update(task.id, { prNumber: pr.number });
  if (pr.created) await deps.events.emit({ type: 'github.pr.created', ...base(ctx), payload: { number: pr.number, url: pr.url } });
  return passed(`${pr.created ? 'Opened' : 'Updated'} pull request #${pr.number}.`);
};

export const ciStage: StageHandler = async (ctx) => {
  const { deps, options, run } = ctx;
  const cp = run.checkpoint;
  const sha = cp.commitSha;
  if (!sha) return { kind: 'blocked', reason: 'No pushed commit to check.' };

  const report = await ctx.tools.invoke<CheckReport>('ci.status', { sha }, orchestratorContext(ctx));
  switch (report.state) {
    case 'success':
      cp.ciPolls = 0;
      cp.ciAttempts = 0;
      cp.verification = { status: 'passed', source: 'ci', summary: 'CI checks passed.' };
      await deps.events.emit({ type: 'ci.passed', ...base(ctx), payload: { sha } });
      return passed('CI checks passed.');

    case 'none':
      cp.ciPolls++;
      if (cp.ciPolls > options.maxCiPollsWithoutChecks) {
        cp.verification ??= { status: 'deferred', source: 'none', summary: 'No CI checks were reported for the commit.' };
        return passed('No CI checks reported for the commit; continuing without CI.');
      }
      return pollLater(ctx, 'Waiting for CI checks to be registered.');

    case 'pending':
      if (cp.ciPolls === 0) await deps.events.emit({ type: 'ci.started', ...base(ctx), payload: { sha } });
      cp.ciPolls++;
      return pollLater(ctx, 'CI is running.');

    case 'failure': {
      const classification = classifyCiFailure({ conclusion: report.conclusion, jobs: report.jobs, logExcerpt: report.logExcerpt });
      await deps.events.emit({ type: 'ci.failed', ...base(ctx), payload: { sha, classification: classification.kind } });

      const rerun = async (why: string): Promise<StageOutcome> => {
        await ctx.tools.invoke('ci.rerun', { runIds: report.runIds }, orchestratorContext(ctx));
        cp.ciAttempts++;
        cp.ciPolls = 0;
        return pollLater(ctx, `${why}; re-running CI without code changes.`);
      };

      // Infrastructure failures never reach the debug agent (spec §32).
      if (classification.kind === 'infra') {
        if (classification.retryable && cp.ciAttempts < options.maxCiInfraRetries && report.runIds.length > 0) {
          return rerun(`CI infrastructure failure (${classification.signals.join(', ')})`);
        }
        return { kind: 'blocked', reason: `CI infrastructure failure needs attention: ${classification.reason}` };
      }
      if (classification.kind === 'unknown' && cp.ciAttempts === 0 && report.runIds.length > 0) {
        return rerun('Unclassified CI failure');
      }

      cp.ciAttempts = 0;
      const output = truncate(redactSecrets(report.logExcerpt), 20_000);
      cp.verification = { status: 'failed', source: 'ci', summary: `CI failed: ${classification.reason}`, output: truncate(output, 8_000) };
      return { kind: 'retry', resumeStage: 'COMMIT', summary: `CI failed: ${classification.reason}`, failureOutput: output };
    }
  }
};

export const deployStage: StageHandler = async (ctx) => {
  const { deps, project, run } = ctx;
  const cp = run.checkpoint;
  const workflow = project.profile.deployWorkflow;
  if (!workflow || !cp.prNumber || !project.repo) return passed('Nothing to deploy.');
  if (cp.deployDispatchedAt) return passed('Deployment already dispatched.');

  const notReady = await releaseReadiness(ctx);
  if (notReady) return notReady;
  const readiness = parseOutput(ReleaseReadinessOutputSchema, cp.outputs.release);

  try {
    await ctx.tools.invoke('deploy.run', { prNumber: cp.prNumber, workflow, ref: project.repo.defaultBranch }, orchestratorContext(ctx));
  } catch (error) {
    if (error instanceof ToolDeniedError && error.reason === 'approval_required') {
      return requestApproval(ctx, 'production_deploy', `CI passed for pull request #${cp.prNumber}; ready for production deployment.`, {
        prNumber: cp.prNumber,
        prUrl: cp.prUrl,
        workflow,
        releaseReadiness: readiness ? { summary: readiness.summary, checks: readiness.checks } : null,
      });
    }
    throw error;
  }
  cp.deployDispatchedAt = ctx.now.toISOString();
  await deps.events.emit({ type: 'deployment.started', ...base(ctx), payload: { workflow } });
  return passed(`Merged #${cp.prNumber} and dispatched ${workflow}.`);
};

export const monitorStage: StageHandler = async (ctx) => {
  const { deps, project, run } = ctx;
  const workflow = project.profile.deployWorkflow;
  if (!workflow || !project.repo) return passed('Nothing to monitor.');

  const workflowRun = await deps.github.getLatestWorkflowRun(project.repo, workflow, project.repo.defaultBranch);
  if (!workflowRun || workflowRun.status !== 'completed') return pollLater(ctx, 'Deployment in progress.');

  const conclusion = workflowRun.conclusion ?? 'unknown';
  await deps.events.emit({ type: 'deployment.completed', ...base(ctx), payload: { workflow, conclusion } });
  if (conclusion === 'success') {
    run.checkpoint.outcome = 'deployed';
    return passed('Deployment succeeded.');
  }
  return { kind: 'blocked', reason: `Deployment finished with "${conclusion}". A human decides next steps; no automatic code changes after a production failure.` };
};
